
(define (problem test-goal-3)
  (:domain toy-warehouse-robot-version-3)
  (:objects
   blue red green - box
   centre left right - pos
   )
  (:init
   (on-shelf green left)
   (on-shelf red centre)
   (on-shelf blue right)
   (next-to left centre)
   (next-to centre right)
   (robot-at centre)
   (lift-is-down)
   (gripper-folded)
   )
  (:goal (and
	  (on-shelf blue left)
	  (on-box green blue)
	  (on-shelf red centre)
	  ))
  )

;; (:plan
;;  (move-right centre right)
;;  (unfold-gripper right)
;;  (take-box-from-shelf blue right)
;;  (raise-lift )
;;  (move-left right centre)
;;  (move-left centre left)
;;  (put-box-on-box blue green left)
;;  (move-right left centre)
;;  (lower-lift centre)
;;  (take-box-from-shelf red centre)
;;  (move-right centre right)
;;  (put-box-on-shelf red right)
;;  (fold-gripper right)
;;  (raise-lift )
;;  (move-left right centre)
;;  (move-left centre left)
;;  (unfold-gripper left)
;;  (take-box-from-box blue green left)
;;  (move-right left centre)
;;  (lower-lift centre)
;;  (put-box-on-shelf blue centre)
;;  (raise-lift )
;;  (move-left centre left)
;;  (lower-lift left)
;;  (take-box-from-shelf green left)
;;  (raise-lift )
;;  (move-right left centre)
;;  (move-right centre right)
;;  (put-box-on-box green red right)
;;  (move-left right centre)
;;  (lower-lift centre)
;;  (take-box-from-shelf blue centre)
;;  (move-left centre left)
;;  (put-box-on-shelf blue left)
;;  (fold-gripper left)
;;  (raise-lift )
;;  (move-right left centre)
;;  (move-right centre right)
;;  (unfold-gripper right)
;;  (take-box-from-box green red right)
;;  (move-left right centre)
;;  (move-left centre left)
;;  (put-box-on-box green blue left)
;;  (move-right left centre)
;;  (move-right centre right)
;;  (lower-lift right)
;;  (take-box-from-shelf red right)
;;  (move-left right centre)
;;  (put-box-on-shelf red centre)
;;  )
